services:
  led2mqtt:
    image: ghcr.io/darkson95/led2mqtt:latest
    container_name: led2mqtt
    devices:
      - /dev/gpiomem
    restart: always
    environment:
      MQTT_HOST: # default: localhost
      MQTT_PORT: # default: 1883
      MQTT_WEBSOCKETS: # default: false, options: true, false
      MQTT_USERNAME: # default: empty
      MQTT_PASSWORD: # default: empty
      MQTT_TOPIC: # default: led2mqtt
      MQTT_DISCOVERY_TOPIC: # default: homeassistant

      HA_DEVICE_NAME: # default: LED Strips
      HA_DEVICE_MANUFACTURER: # default: LED2MQTT
      HA_DEVICE_MODEL: # default: LED Strips
      HA_DEVICE_UNIQUE_ID: # default: LED2MQTT_LEDSTRIPS

      LED_GPIO_RED: # default: 23
      LED_GPIO_GREEN: # default: 24
      LED_GPIO_BLUE: # default: 25

      LOG_LEVEL: # default: INFO, options: NOTSET, DEBUG, INFO, WARNING, ERROR, CRITICAL
